# Приложение должно понимать в каком окружении его запускают: local, dev, prod
env: "local"

# Путь до файла в котором будет храниться база данных (это для sqlLite)
storagePath: "./storage/storage.db"

# Далее конфиг сервера
httpServer:
  address: "localhost:9000"
  # timeout - время на чтение запроса и такое же время на отправку ответа
  timeout: 5s
  # idle_timeout - время жизни соединения с клиентом,
  # удобно, когда от одного клиента несколько запросов и между ними немного времени прошло
  # открываем соединение на 60s для одного клиента и он может присылать несколько запросов
  idleTimeout: 60s