CREATE TABLE IF NOT EXISTS "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "username" varchar(255) UNIQUE NOT NULL DEFAULT 'noname',
    "password_hash" varchar(255) NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "is_deleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "chat" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "name" varchar(255) UNIQUE NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "is_deleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "message" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "text" varchar(255) NOT NULL,
    "user_id" integer NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "is_deleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "users_chat" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "user_id" integer NOT NULL,
    "chat_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "chats_messages" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "users_chat_id" integer NOT NULL,
    "message_id" integer NOT NULL
);


ALTER TABLE "users_chat" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION;

ALTER TABLE "users_chat" ADD FOREIGN KEY ("chat_id") REFERENCES "chat" ("id") ON DELETE CASCADE;

ALTER TABLE "chats_messages" ADD FOREIGN KEY ("users_chat_id") REFERENCES "users_chat" ("id") ON DELETE NO ACTION;

ALTER TABLE "chats_messages" ADD FOREIGN KEY ("message_id") REFERENCES "message" ("id") ON DELETE CASCADE;

ALTER TABLE "message" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION;


-- функция для удаления сообщений
CREATE OR REPLACE FUNCTION delete_message(userID integer, VARIADIC msgID integer[]) RETURNS TABLE(identifier integer, result text) AS
$$
DECLARE
    idMsg integer := 0;
    errExist text := 'Message does not exist or has already been deleted';
    success text := 'Message successfully deleted';
BEGIN
    -- если сообщения не существуют - отправляем ошибку
    IF NOT EXISTS(
        SELECT *
        FROM message
        WHERE user_id = userID
        AND id = ANY (msgID)
    )
    THEN
        RAISE EXCEPTION 'Not found messages';
    END IF;

    -- временная таблица для хранения результата update
    CREATE TEMPORARY TABLE IF NOT EXISTS updated_msg(
        id integer,
        res text
    );

    -- удаляем сообщения, если не существуют или уже удалены - отправляем ошибку
    FOREACH idMsg IN ARRAY msgID
        LOOP
            -- удаляем сообщение
            UPDATE message
            SET is_deleted = true
            WHERE id = idMsg
            AND is_deleted = false;
            -- если нет такой записи или уже удален, то добавляем (id,ошибка) в таблицу updated_msg
            IF NOT found THEN
                INSERT INTO updated_msg(id, res)
                VALUES (idMsg, errExist);
            ELSE
                -- если запись есть и не удалена, то добавляем (id,success) в таблицу updated_msg
                INSERT INTO updated_msg(id, res)
                VALUES (idMsg, success);
            END IF;
        END LOOP;

    -- возвращаем итоговый результат
    RETURN QUERY SELECT id AS rec, res AS result
                 FROM updated_msg;

    -- удаляем временную таблицу
    DROP TABLE updated_msg;
END;
$$
LANGUAGE plpgsql;
